### PR TITLE
Config reader

### LINKED ISSUE #2: Extract postgres monitoring to rust module
SRP is broken here. It's needed to be fixed

### PR DESCRIPTION
**Pull request by anton-okolelov**
Extracted config reading to module

closes #2

### CODE REVIEW

**Comment by hack3p** [comment]
Good changes. Could you install and apply [rustfrm](https://github.com/rust-lang-nursery/rustfmt)?

**Comment by anton-okolelov** [comment]
Of course!

**Comment by anton-okolelov** [comment]
Done

**Comment by hack3p** [comment]
Very well!

**Pull request merged**
